### PR TITLE
Allow proto imports in different directories

### PR DESCRIPTION
**Pull request by CGA1123**
This commit updates the way which `import` paths are generated in order
to allow imports across different directories. It does this by
generating a relative path from the file being generated and the import
dependency, assuming that the generated file and its dependency share
the same root.

### CODE REVIEW

**Comment by CGA1123** [comment]
An example of where this is useful is for example with a structure as is present in https://github.com/summer-fruits/buf where `juice/v1/juice.proto` depends on `summerfruits/v1/summerfruits.proto` as well as `google/protobuf/timestamp.proto` (as a well-known type).

The effective change in the generated code is like this:

```diff
// dart/juice/v1/juice.pbtwirp.dart
- import "summerfruits/v1/summerfruits.pb.dart"
- import "google/protobuf/timestamp.pb.dart"
+ import "../../summerfruits/v1/summerfruits.pb.dart"
+ import "../../google/protobuf/timestamp.pb.dart"
```

A full diff can be seen in this commit: https://github.com/summer-fruits/buf/commit/16afcc26cf3a2e0c7ebbff313c4354cf595c6936

**Comment by sschwartz96** [comment]
Hi @CGA1123, thank you for submitting your PR! 

It looks good to me but I'd like to be able to test this against a similar setup like the repo you listed.

Could you please let me know how you set up your protoc command to generate the files in your example repo?? I keep getting some strange errors.

Thanks!

**Comment by sschwartz96** [comment]
I cloned summer-fruits/buf on the cga1123/tart-comparison branch and attempted to run the protoc command as follows:
```
protoc --tart_out=./dart \
        --dart_out=./dart \
        -I . \
        ./juice/v1/juice.proto \
        ./summerfruits/v1/summerfruits.proto
```

This was the first error I received:
```
protoc-gen-tart: unable to determine Go import path for "summerfruits/v1/summerfruits.proto"

Please specify either:
        • a "go_package" option in the .proto source file, or
        • a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--tart_out: protoc-gen-tart: Plugin failed with status code 1.
```

I think this is a side effect of using the `google.golang.org/protobuf/compiler/protogen` to parse the proto file.
So to work around this I add `option go_package = "summerfruits/v1";` to the summerfruits.proto and `option go_package = "juice/v1";` to the juice.proto file.

I tried to compile the protos again and was greeted with this error:
```
juice/v1/juice.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-tart hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--tart_out:
```
I don't think this is something that we have to worry about when compiling protobuf files for Twirp.
I looked how the protoc_gen_go plugin notified that it supported the "proto3" features and added this line to the tart plugin:
https://github.com/protocolbuffers/protobuf-go/blob/6875c3d7242d1a3db910ce8a504f124cb840c23a/cmd/protoc-gen-go/main.go#L54

I compiled again and success!
Here is the tree output of the summer-fruits/buf/dart directory after removing the originally generated files and compiling with the above protoc command after edits to the proto files and ensuring that the Tart protoc plugin "supports" proto3 features.
```
 dart
│   ├──  juice
│   │   └──  v1
│   │       ├──  juice.pb.dart
│   │       ├──  juice.pbenum.dart
│   │       ├──  juice.pbjson.dart
│   │       ├──  juice.pbserver.dart
│   │       └──  juice.pbtwirp.dart
│   └──  summerfruits
│       └──  v1
│           ├──  summerfruits.pb.dart
│           ├──  summerfruits.pbenum.dart
│           ├──  summerfruits.pbjson.dart
│           └──  summerfruits.pbserver.dart
```

Curious to see your process of compiling the protobuf files.

**Comment by CGA1123** [comment]
Hey @sschwartz96 sorry I didn't get around to getting you the `protoc` command quickly!

The example project doesn't use the `protoc` compiler, it uses `buf` (https://buf.build) which handles a lot of the finicky parts of `protoc` 😄 That's what the `buf.gen.yaml` and `buf.yaml` files setup in that example project, allowing generation to be taken care of via `buf generate --include-imports --include-wkt`

**Comment by sschwartz96** [comment]
@CGA1123 

Ahhh, I was wondering about the buf files were all about, I will have to check out this tool cause protoc is painful at times.

In this case I'll merge this PR and create a new one for the commenting issue and I think this should work. Thank you!

**Pull request merged**
